#34 #35 mapper
develhope/chooseyourowncocktail pull request #44
Opened 2022-05-02 16:15 UTC by Francesco96it

Created Mapper Function, DTO Models and Network Call for retrieve Drinks

2022-05-18 19:56 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/DrinksDB.kt
> +object DrinksDB {
Perchè lo chiami DrinkDB? Io che atterro su questo mi aspetto un database ma in realtà ho delle chiamate di rete

2022-05-19 06:09 UTC, vincenzocostagliola reviewed
Questi sono i primi commenti

2022-05-19 06:09 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/network/DrinkDao.kt
> +interface DrinkDao {
Perchè questo nome, sono chiamate di rete e non un oggetto di un databse

2022-05-19 06:09 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/network/DrinkDao.kt
> +    @GET("https://www.thecocktaildb.com/api/json/v1/1/lookup.php")
Se nel client c'è la base url non serve avere il l'endpoint completo qui

2022-05-19 06:09 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/model/domainmodel/drinks/DrinkResultModel.kt
> +data class DrinkResultModel(
Non mi è chiaro l'utilizzo di questo modello, se rappresenta il modello di dominio della ui, è in realtà un doppione, perchè la ui  è basata su Beer.kt ( che ovviamente può cambiare nome)

2022-05-19 12:50 UTC, vincenzocostagliola requested changes
In DrinksDB ci sono troppe funzioni con relative chiamate di rete. L'idea iniziale deve essere più semplice per poi eventualmente evolvere.
Avevamo detto, se ricordo bene, di prendere una lista di drink data una lettera specifica e tenerli in memoria per l'uso corrente, (salavrlo nelloggetto beers)
Direi che può essere un primo passo. 
il mapper deve tenere conto anche degli errori sia di rete che di altro tipo. modellerei il tipo ritornato con una sealed class che mappa verso il modello della ui

2022-05-19 12:50 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/DrinksDB.kt
> +    suspend fun getByIDList(idList: DrinkResult): DrinkResult {
DrinkResult è il tipo ritornato, perchè passi nel costruttore un oggetto DrinkResult?

2022-05-19 12:50 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/DrinksDB.kt
> +            val result = RestClient.getClient().create(DrinkDao::class.java)
Potresti raggruppare in un valore RestClient.getclient()

2022-05-19 13:24 UTC, Francesco96it commented on app/src/main/java/co/develhope/chooseyouowncocktail_g2/DrinksDB.kt
> +    suspend fun getByIDList(idList: DrinkResult): DrinkResult {
Perchè tramite le chiamate 'filter' dell'API che stiamo utilizzando restituiscono solo nome, id e image url del drink,
quindi prendo gli id dei drink ottenuti e li chiamo singolarmente tramite getDrinkByID()
Sicuramente una chiamata di rete per ogni drink non è l'ideale, rallenta molto, ma non ho trovato altra soluzione

2022-05-23 11:32 UTC, closed without merging